### ISSUE TITLE
The ground truth of the Biccoca

### ISSUE THREAD

**Issue by LiYingOne** [ktsintotas/assigning-visual-words-to-places#1]
Thank you for your sharing.Could you please tell me how to get the ground truth of the bicocca and KITTI dataset ?Thank you.

**Comment by ktsintotas** [comment]
Please send me a personal e-mail in order to send them to you.

**Comment by LiYingOne** [comment]
> Please send me a personal e-mail in order to send them to you.

Thank you very much. My e-mail is ly_zs0315@126.com.
